### ISSUE TITLE
Feature request: powershell output (so we can where, select etc)

### ISSUE THREAD

**Issue by mikemaccana** [lowleveldesign/wtrace#1]
Heya! This is an awesome tool. This isn't so much of as issue as a feature request: it would be excellent to be able to do something like:

    wtrace mspaint | where {$_.syscall -eq "FileIO/Close" }

Or similar.

**Comment by lowleveldesign** [comment]
That is an excellent idea! I will look into it in the nearest future.

**Comment by ygra** [comment]
You could [emit CLIXML](https://github.com/PowerShell/PowerShell/issues/1999#issuecomment-263386482) with a switch on the command line which PowerShell can natively interpret and deserialize back into its own data structures.

**Comment by lowleveldesign** [comment]
@ygra thank you! I haven't heard about CLIXML, and it seems to be a neat way to accomplish Powershell integration. I plan to work on this feature this week and will update you with the results. The only thing that worries me right now about CLIXML is that it might be too slow for the number of events wtrace generates.

**Comment by ygra** [comment]
Well, you can't stream it. That's probably a problem. It also comes with a lot of overhead. CSV may be smaller, but less flexible, as you have to have an explicit parsing step, you only have strings (so operators like `-gt` on columns that are actually numbers don't really work).

So perhaps a PowerShell module that acts as a wrapper might be a better approach. Run the native command, parse the output and generate objects that can be further filtered or worked with down the pipeline. I guess any approach that has to first consume everything might not work here.

If parsing performance is a problem you could even write the parsing and object generation code in C# and just call that from PowerShell within your module.

**Comment by lowleveldesign** [comment]
@mikemaccana @ygra thank you again for your input and ideas. Please have a look at [the newest release](https://github.com/lowleveldesign/wtrace/releases/tag/1.3) and [updated wiki](https://github.com/lowleveldesign/wtrace/wiki/PowerShell-support). I hope that the output is OK with you.

Unfortunately, because of the way PowerShell handles Ctrl+C, it is not possible to gracefully end a tracing session with Ctrl+C - it will be immediately stopped, with no summary events printed. I struggled to make it work, but after many trials I gave up.
